language: common-lisp
sudo: false

addons:
  apt:
    packages:
    - zip

env:
  global:
  - GAMEKIT_SYSTEM_NAME: slimeit
  - GAMEKIT_APPLICATION_PACKAGE: fistmage.game
  - GAMEKIT_APPLICATION_MAIN_CLASS: slimeit
  - PATH: ~/bin/:$PATH
  - GAMEKIT_TARGET_PACKAGE: $GAMEKIT_SYSTEM_NAME-x86-64-$TRAVIS_OS_NAME-$TRAVIS_BRANCH.zip
  - GAMEKIT_BUILD_DIR: /tmp/$GAMEKIT_SYSTEM_NAME
  - secure: ""

branches:
  only:
    - "/^v\\d+(\\.\\d+)+$/"

os:
  - linux
  - osx

install:
  - curl -L http://bodge.borodust.org/files/install.sh | sh -s ccl

cache:
  directories:
  - "$HOME/.config/common-lisp/"

script:
  - >
    lisp $HOME/bodge/scripts/build-experimental-gamekit-system.lisp
    $GAMEKIT_SYSTEM_NAME $GAMEKIT_APPLICATION_PACKAGE $GAMEKIT_APPLICATION_MAIN_CLASS
    $TRAVIS_BUILD_DIR
    $GAMEKIT_BUILD_DIR
    t

before_deploy:
  - mv "$GAMEKIT_BUILD_DIR/$GAMEKIT_SYSTEM_NAME.zip" $GAMEKIT_TARGET_PACKAGE

deploy:
  provider: releases
  api-key: $GITHUB_TOKEN
  file: $GAMEKIT_TARGET_PACKAGE
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
